### ISSUE TITLE
Adding the Initial Migration Fails

### ISSUE THREAD

**Issue by engxladso** [PacktPublishing/ASP.NET-Core-3-and-Angular-9-Third-Edition#14]
Even though Microsoft.EntityFrameworkCore.Design is installed and can be seen within WorldCities/Dependencies/Packages and WorldCities is the only project, dotnet ef migrations run from the WorldCities root folder still fails with:

"Your startup project 'WorldCities' doesn't reference Microsoft.EntityFrameworkCore.Design." In fact when I run the migration command from the book, I see it remove this package from the Packages folder!

Microsoft documentation basically admits that dotnet ef migrations are unreliable in its documentation and suggests using the package manager console instead. If you can provide a package manager console version of the migration commands from the book, that would be very helpful.

**Comment by Darkseal** [comment]
Hello there,
sorry for the late reply.

Have you tried the various fixes & workaround mentioned in this SO thread?

https://stackoverflow.com/questions/52536588/your-startup-project-doesnt-reference-microsoft-entityframeworkcore-design

It seems like the issue is related to the project not being set as default (or not be seen as such by the dotnet ef CMD).

Anyway, here are the .NET CLI commands described in the book's Chapter 4 and their corresponding Package Manager Console / Powershell versions:

**.NET CLI reference**
    dotnet ef migrations add "Initial" -o "Data/Migrations"
    dotnet ef migrations add "Identity" -o "Data/Migrations"
    dotnet ef database update
    dotnet ef database drop

**Package Manager Console**
    Add-Migration Initial -OutputDir "Data/Migrations"
   Add-Migration Identity -OutputDir "Data/Migrations"
    Update-Database
    Drop-Database

If you need to convert other commands, please read the following official guides:

- EF Core .NET CLI reference: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
- EF Core PMC / PowerShell reference: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell
