### ISSUE TITLE
Chapter 11: Publish WorldCities Fails at webpack.Progress 95% elifecycle of ng build --prod

### ISSUE THREAD

**Issue by engxladso** [PacktPublishing/ASP.NET-Core-3-and-Angular-9-Third-Edition#15]
Been trying to get this to work for a day. Have used WinMerge to copy Chapter 11's code that I downloaded to my own code. Makes no difference. When I try to publish the actual Chapter 11 project it gets past this stage only to fail on a subsequent stage which tries to copy NuGet packages from my version of the WorldCities project to the folder where I downloaded the book to. I guess I will have to completely replace my code with the book version in order to finally get past this stage and hopefully finish the book before I retire!

In the output, there are multiple errors referring to the 'mat-form-field' and its children not being known elements in the cities.component.  All of the stack overflow etc solutions say this is because of modules not being imported, however this is not true in this case as these modules are imported into the angular-materials-module. There are also loads of typescript errors referring mainly to PluginConfig and ProtractorPlugin. It all suggests that some cache has got mixed up. I suspect this may be because I had to downgrade typescript to fix a previous build failure from a previous chapter.

This all reminds me of the 'dll hell' that used to be experienced in the days of classic ASP and COM and more recently when class libraries shared between teams are not maintained properly. This is kind of inevitable when you have loads of disparate teams coding different aspects this technology and trying to make it all work together. It does not endear me to Angular. I wonder if vue.js is this error prone? I suspect it probably is for the same kind of reasons.

Is there a solution which does not involve me overwriting my project from the downloaded project?

Before I finish this, I would like to tell you that I have found the book to be well written and engaging enough to not feel dry and boring at all. I don't often make it to the end when reading IT books, but I have with yours, so thanks for writing this. It has certainly helped me learn the basics of how to include Angular 9 in a .net core project. I will be applying lessons learnt to an app that I am writing now.  

Having said that, I would like to add some what I hope you find to be constructive criticism. 

The 'broken code myth' disclaimer is a little inaccurate. Despite what you say about how carefully the book was written etc, I have found typos, missing bits and differences between the book's text and the downloadable project code. This has led to hours of frustration when the code wouldn't load pages. I would have preferred the debugging chapter to have been much nearer the front of the book, as I am sure it would have helped in situations when the inital page load either timed out or showed cannot GET. 

I am also mystified by the c# code in the SeedController Import() method in the book in which you add "await _context.SaveChangesAsync();" within both for() loops. Any experienced EF developer knows that saving changes one item at a time is very, very inefficient. I amended it by moving the SaveChangesASync() to just below the loops, recreating lstCountries from the context The whole task took a few seconds, not the 15 minutes that you told us to expect. So can you explain why you wrote it this way?

Thanks.

**Comment by Darkseal** [comment]
Hello there,
sorry for the late reply.

First of all, thank you for purchasing the book: I'm glad you've managed to like it despite the hours you've lost to make some of my examples to actually work.

Regarding the "dll hell" issue you're having, I honestly don't know what could have gone wrong: occasionally I also run into such problems but fortunately I can always solve in a few minutes using the visual studio tools (Clear Project and so on) and/or getting back the project from scratch from my GitHub's latest pull. I think that the best thing you can do is to get a "working version" of Chapter 11 by getting it from the book's GitHub repo and then try to replace the json, cs, ts and html files until you get the one that's messing things around (it might be the angular.json file or other configuration files). I agree with you that these configuration issues are a nightmare and that they can easily cripple the whole programming experience of anyone who doesn't have the experience and/or the "StackOverflow grinding" patience required to eventually overcome them.

Regarding the "Broken Code Myth" issue, I think you may have misunderstood the concept I wanted to express in that paragraph. The fact that the book may contain typo or errors is practically inevitable: the myth I'm talking about is not the presence of errors, but the fact that they can seriously compromise the programming experience. From February to September we received over 50 bug reports, which I have personally reviewed: 99% of these were objectively insignificant in terms of understanding the code and could be easily solved by any developer just by observing the intellisense suggestions and acting accordingly: moreover, a **huge** number of them were not even present in the GitHub code, which I've struggled to keep updated and 100% build-capable with the given set of tools. Don't get me wrong, I do realize that in some edge-case scenarios these errors can lead the readers astray and make them waste a lot of time, especially if they don't check the GitHub code everytime something seems odd (general rule: whenever it doesn't compile or doesn't work as expected, it's definitely odd). At the same time, I am 100% convinced that exaggerating those inevitable typos and talking about "hours wasted trying to make a broken code to actually work" is a myth that needs to be defeated, especially when we talk about "differences between the book's text and the downloadable project code". The Broken Code Myth paragraph literally says what to do in this circumstance: _Is the book's GitHub repository also affected by this issue? Did I try to compare it with my own code, possibly replacing mine?_ That said, if you think I'm wrong in saying this, I'll be more than happy to discuss a couple of issues you've had with the book source code and how they took hours to get fixed because of typos or missing bits.

As for the `SeedController`'s `Import()` method, you're definitely right: there is no reason to trigger the DB save upon each iteration, you can do that at the end of each for cycle. I've just released on GitHub a patched version of that method that calls the context's `SaveChangesAsync(`) method a maximum of two times (only if there is at least a new country or city to add). This can be done ever more efficiently using a single call near the end, but I do prefer to have different calls for countries and cities.
