### ISSUE TITLE
Chapter 5 Client Side Paging

### ISSUE THREAD

**Issue by joonjang** [PacktPublishing/ASP.NET-Core-3-and-Angular-9-Third-Edition#16]
Hello,

The client side pagination implemented in chapter 5 for the section "Client-side paging" does not seem functional. The programming done in that section imports the pagination tools, but never uses it so the pagination has no information linked to it. 

The problem seems get resolved once the server-side pagination is implemented later on in the chapter

**Comment by wildmichael** [comment]
I see the same. The paginator is there, it just doesn't do anything.

**Comment by Darkseal** [comment]
Hello there,
thank you for pointing out that issue, which was really difficult to fix in advance since it's related to a bunch of source code that gets updated throughout the same chapter later on and therefore never happened to hit the GitHub repository 👍 

Here's the `cities.component.ts` file fixed source code that makes the client-side pagination work:

```
import { Component, Inject, ViewChild } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';

import { City } from './city';

@Component({
  selector: 'app-cities',
  templateUrl: './cities.component.html',
  styleUrls: ['./cities.component.css']
})
export class CitiesComponent {
  public displayedColumns: string[] = ['id', 'name', 'lat', 'lon'];
  public cities: MatTableDataSource<City>;

  @ViewChild(MatPaginator) paginator: MatPaginator;

  constructor(
    private http: HttpClient,
    @Inject('BASE_URL') private baseUrl: string) {
  }

  ngOnInit() {
    this.http.get<City[]>(this.baseUrl + 'api/Cities')
      .subscribe(result => {
        this.cities = new MatTableDataSource<City>(result);
        this.cities.paginator = this.paginator;
      }, error => console.error(error));
  }
}
```

It goes without saying that you also need to "revert" the changes made to the `cities.component.html` and `CitiesController.cs` files in case you updated them to implement the server-side pagination: their source code is the same described in the book up to pages 224-226 hence they don't need a fix, but they get breaking changes later on in Chapter 5.

I've added a `/ClientApp/src/app/cities/_clientSidePagination/` folder that contains the relevant angular files and a `_README.txt` file explaining how to properly implement the client-side pagination within the Chapter 5 source code for demonstration purposes: you should be 100% able to try it now and see how it works. I've also updated the book content (pages 224-226) so that the next edition will have this fixed as well: thank you again for finding the bug!
